name: 'Update the vector database'

on:
  repository_dispatch:
    types: [oracle-release]

jobs:
  dependent_job:
    runs-on: ubuntu-latest
    steps:
      - name: "do stuff"
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          echo Oracle version $VERSION released!